patternDefinitions:
  #3D
  '999': XXX
  AAA: AAA
  ABC: ABC[isSequential:true]
  ABB: ABB
  ABA: ABA
  AAB: AAB
  360Degree: XXX°[min:0;max:360]

  '0x999': (0x)(XXX[base:hex])
  999JP: XXX[digitSet:JP]
  999CN: XXX[digitSet:CN]
  Arabic999: XXX[digitSet:AR]
  # Only 22 specific flags, as per https://rare.id
  Flag999: (X[digitSet:FlagEmojiSet0])(XXX)

  #4D
  10k: XXXX
  ABCD: ABCD[isSequential:true]
  AAAA: AAAA
  ABBB: ABBB
  AABB: AABB
  AAAB: AAAB

  ABAA: ABAA
  AABA: AABA
  ABBA: ABBA
  ABAB: ABAB
  AABC: AABC
  ABCC: ABCC
  ABBC: ABBC

  0XXX: 0XXX
  00XX: 00XX
  0X0X: 0X0X
  0XX0: 0XX0
  XX00: XX00
  XX88: XX88
  XX69: XX69

  TimesTable: XXXX[_CUSTOM_TimesTable:true]
  MMDD: XXXX[_CUSTOM_MMDD:true]
  0x10k: (0x)(XXXX[base:hex])
  Arabic10k: XXXX[digitSet:AR]

  #5D
  100k: XXXXX
  AAAAA: AAAAA
  ABCDE: ABCDE[isSequential:true]
  ABBBB: ABBBB
  AABBB: AABBB
  AAABB: AAABB
  AAAAB: AAAAB

  ABBBA: ABBBA
  ABAAA: ABAAA
  AABAA: AABAA
  AAABA: AAABA
  ABABA: ABABA
  XABCD: (X)(ABCD[isSequential:true])
  XX000: XX000

  00XX0: 00XX0
  000XX: 000XX
  XX420: XX420
  AAABC: AAABC
  AABBC: AABBC
  AABCC: AABCC
  ABCCC: ABCCC

  ABBCC: ABBCC
  ABBBC: ABBBC
  ABCBA: ABCBA
  XXX69: XXX69
  69XXX: 69XXX
  00XXX: 00XXX
  XXX00: XXX00

  #6D
  AAAAAA: AAAAAA
  ABBBBB: ABBBBB
  AABBBB: AABBBB
  AAABBB: AAABBB
  AAAABB: AAAABB
  AAAAAB: AAAAAB
  ABBABB: ABBABB

  ABABAB: ABABAB
  00XX00: 00XX00
  AABBCC: AABBCC
  ABCCCC: ABCCCC
  ABBBBC: ABBBBC
  AAAABC: AAAABC
  ABCABC: ABCABC

  XXX420: XXX420
  420XXX: 420XXX
  XXX000: XXX000
  000XXX: 000XXX
  #Ashare code range 000000-000999, 600000-601999, 603000-603999
  AShareCode: (000XXX)|(60XXXX[min:0;max:1999])|(60XXXX[min:3000;max:3999])
  XXXX69: XXXX69

  #>6D
  AAABBBB: AAABBBB
  AAAABBBB: AAAABBBB
  ABBCBBA: ABBCBBA
  WanClub: X0000[min:1]|XX0000[min:10]|XXX0000[min:100]
  # On https://rare.id/search?tab=category
  # XXXAAAAAAAA has 420 possible numbers, which means XXX has 42 specific combinations without apparant reasoning
  XXXAAAAAAAA: 139AAAAAAAA|138AAAAAAAA|137AAAAAAAA|136AAAAAAAA|135AAAAAAAA|134AAAAAAAA|159AAAAAAAA|158AAAAAAAA|157AAAAAAAA|152AAAAAAAA|151AAAAAAAA|150AAAAAAAA|188AAAAAAAA|187AAAAAAAA|184AAAAAAAA|183AAAAAAAA|182AAAAAAAA|178AAAAAAAA|172AAAAAAAA|198AAAAAAAA|195AAAAAAAA|147AAAAAAAA|186AAAAAAAA|185AAAAAAAA|155AAAAAAAA|156AAAAAAAA|130AAAAAAAA|131AAAAAAAA|132AAAAAAAA|176AAAAAAAA|175AAAAAAAA|166AAAAAAAA|145AAAAAAAA|133AAAAAAAA|153AAAAAAAA|189AAAAAAAA|181AAAAAAAA|180AAAAAAAA|177AAAAAAAA|173AAAAAAAA|199AAAAAAAA|191AAAAAAAA

  #0xDigits
  '0x9': (0x)(X[base:hex])
  '0x99': (0x)(XX[base:hex])
  # 0x999, 0x10k appeared before
  1Hex: (0x)(X[base:hex;digitSet:hex])
  2Hex: (0x)(XX[base:hex;digitSet:hex])
  3Hex: (0x)(XXX[base:hex;digitSet:hex])
